In [1]:
!pip install torch torchvision torchaudio

  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/203.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/203.0 MB 10.2 MB/s eta 0:00:20
   ---------------------------------------- 0.9/203.0 MB 11.2 MB/s eta 0:00:19
   ---------------------------------------- 1.3/203.0 MB 10.5 MB/s eta 0:00:20
   ---------------------------------------- 1.9/203.0 MB 10.9 MB/s eta 0:00:19
   ---------------------------------------- 2.4/203.0 MB 11.0 MB/s eta 0:00:19
    --------------------------------------- 3.0/203.0 MB 11.1 MB/s eta 0:00:19
    --------------------------------------- 3.5/203.0 MB 11.2 MB/s eta 0:00:18
    --------------------------------------- 4.0/203.0 

In [2]:
import torch
import numpy as np

### Torch Init

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

**From a Numpy Array**

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another Tensor**

In [7]:
import torch.random


x_ones = torch.ones_like(x_data)
print(f"One Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

One Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9606, 0.9430],
        [0.3836, 0.6242]]) 



**With Random or Constant Values**

In [8]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)

print(f"Rand Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zero Tensor: \n {zeroes_tensor} \n")

Rand Tensor: 
 tensor([[0.2803, 0.0622, 0.7104],
        [0.9429, 0.1386, 0.7320]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Tensor Attributes

In [9]:
tensor = torch.rand(3, 4)

print(f"Shape of the Tensor: \n {tensor.shape}\n")
print(f"Datatype of the Tensor: \n {tensor.dtype}\n")
print(f"Device of the Tensor: \n {tensor.device}\n")

Shape of the Tensor: 
 torch.Size([3, 4])

Datatype of the Tensor: 
 torch.float32

Device of the Tensor: 
 cpu



### Tensor Operations

**Standard Numpy like Indexing and Slicing**

In [11]:
tensor = torch.ones(4, 4)
tensor[:, 3] = 0
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


**Join Tensors**

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


**Element wise Tensor Multiplication**

In [14]:
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor: \n {tensor * tensor} \n")

tensor.mul(tensor): 
 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

tensor * tensor: 
 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 



**Matrix Multiplication**

In [15]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")


tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**Inplace Operations**

In [17]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]]) 

tensor([[11., 11., 11., 10.],
        [11., 11., 11., 10.],
        [11., 11., 11., 10.],
        [11., 11., 11., 10.]])


### Bridge with Numpy

**Changes in Tensor reflect in Numpy array**

In [18]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


**Changes in numpy array reflect in the Tensor**

In [19]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
